### ISSUE TITLE
请问这个方法可以获得cpu/硬盘的温度数据吗？

### ISSUE THREAD

**Issue by s450586793** [neroxps/esxi_monitor_to_json#1]
你好，我是J4105的主板跑的esxi，没有ipmi，查不到温度有点头大，请问这个方法可以加入cpu已经硬盘的温度数据吗？
另外，我按照主页的方法，获得了esxi上的硬盘数据，然而我其他的数据盘是rdm方式直通给了群晖，这个方法似乎拿不到相应的数据

**Comment by neroxps** [comment]
不太清楚，我已经逃到 pve了。

**Comment by s450586793** [comment]
您的来信已收到。谢谢。--------------江阴市万禾铝业科技有限公司   吴孝斌

**Comment by corsgoo** [comment]
> 不太清楚，我已经逃到 pve了。

作者闲暇之余可以继续看看 更新一下嘛 ，esxi看 数据太难了

**Comment by s450586793** [comment]
您的来信已收到。谢谢。--------------江阴市万禾铝业科技有限公司   吴孝斌
